### ISSUE TITLE
Reusing existing standards in the specification

### ISSUE THREAD

**Issue by cmdoret** [MrHedmad/data-myr#1]
Hi @MrHedmad,

I really like the idea of myr and it looks promising. My experience with ro-crate has been similar in the past.
I had a few questions / suggestions regarding the specification.

The contents of "specification" in metadata.json look a lot like [jsonschema](https://json-schema.org/). Is there any reason not to reuse [a subset of] jsonschema directly? This would allow reusing existing validators. From your example, I think the jsonschema may look something like this, do you think it is too verbose / obscure for users?

```json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "definitions": {
    "person": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string",
          "description": "The name of a real person."
        },
        "ORCID": {
          "type": "string",
          "pattern": "^\\d{4}-\\d{4}-\\d{4}-\\d{4}$",
          "description": "An ORCID id."
        },
        "email": {
          "type": "string",
          "format": "email",
          "description": "An e-mail address."
        }
        "type": {
          "type": "string",
          "enum": ["person"]
        }
      },
      "required": ["name", "type"]
    },
    "file": {
      "type": "object",
      "properties": {
        "path": {
          "type": "string",
          "description": "The path to the file."
        },
        "MIME_type": {
          "type": "string",
          "description": "The MIME type of the file."
        },
        "author": {
          "$ref": "#/definitions/person",
          "description": "The author of the file."
        },
        "date": {
          "type": "string",
          "format": "date",
          "description": "The date the file was created."
        },
        "type": {
          "type": "string",
          "enum": ["file"]
        }
      },
      "required": ["path", "MIME_type", "type"]
    }
  }
}
```

The concept of remote keys being expanded in frozen copies is really nice. It seems this can also be done with jsonschema using [pointers](https://json-schema.org/understanding-json-schema/structuring.html) but I've never tried it.

Alternatively, since you mention schema.org, what do you think of json-ld / rdf? In the README, you mentioned

> Then, once (and if) a global standard is defined, you can migrate your data to that standard (in some way).

RDF can help with this and there are even tools like [SSOM](https://github.com/mapping-commons/sssom/tree/master) that make this easier. RDF / json-ld is a bit hard to understand / write and so may not be a good solution for data entry but might be interesting as an export format for frozen bundles? Not sure if that would make sense.

Maybe all that is too complex / out of scope, just wanted to hear your thoughts on it :)

**Comment by MrHedmad** [comment]
Hello! Thank you so much for taking the time of opening an issue.

As I also say in the README (or somewhere), I think that reusing standards is a must.
I had not known about `jsonschema` (whoops!). It looks really promising, and as you point out, it would be wise to reuse it, and I broadly think it would also be a good addition to the spec.

However, I want a specification that could be read and written by anyone (with a touch of training, of course), especially people who do not work outside of Google Docs, Word and occasionally PRISM (like the wet-lab researchers in my group).
This is why `RO-crate`, `json-ld` and similar specs did not satisfy me. While `jsonschema` is a bit easier, I'm also afraid that it is too much. The pros I see would be:
- We reuse a schema that is already there, so we get tools for free;
- The spec allows for stricter checking of types and formats, which is a very, very good thing. Potentially an essential thing.

But I also see some cons:
- It's (a bit) too complex to write. I was also borderline at complexity with the `required` and `valid_values` keys, so extending it to `format`, `pattern` etc... is too much.
- Needing to have the `{type: {"type": "string", "enum": ["person"]}}` is redundant. This is the same concern as with RO-crate having the entry of the metadata file itself + the entry for the bundle as a whole.
- I don't see a way of reusing keys in different `definitions`. Is there a way to do this? It might help for omonim keys, but I would like to avoid those if possible.
- Having the ability to add more keys to the bundle than the ones specified by the structure is a must for me. Would that be possible with jsonschema?
- The "having multiple specifications in a list" (e.g. `{"@specification": ["url", "url2"]}`) "feature" of `myr` is really nice, IMO. This way, we can create and mix/match different sets of specifications for different use-cases. E.g. we could make a "base" spec and various experiment-type specific specifications, and write `{"@specification": ["base.json", "microscopy.json"]}`. Would `jsonschema` be easily "summed"? I think so, but :shrug:.

This said, it could be a nice format to adhere to, but we would then have to have an extra step in our metadata workflow:
- We sit down and decide what to record;
- We produce a `"specification"`;
- `myr` makes an empty `.txt` (toml? Yaml?) file with all the keys / values / requirements in a human-readable format (with emojis, maybe?)
- The researcher records the variables during the experiment
- `myr` takes this `.txt` file and parses it, and makes the working copy / frozen copy of the bundle.

The extra abstraction step would make the actual implementation (like the `jsonschema`) irrelevant for the researcher, so it allows more freedom machine-wise. But it would need quite a bit of extra programming to make.

I hope I was clear enough. Let me know what you think!

**Comment by cmdoret** [comment]
First, to answer your questions about jsonschema:

> I don't see a way of reusing keys in different definitions. Is there a way to do this?

I think you would do this with [$def](https://json-schema.org/understanding-json-schema/structuring.html#defs)

> the ability to add more keys to the bundle than the ones specified by the structure is a must for me. Would that be possible with json schema 

I believe additional properties are allowed by default ([but can be disabled if needed](https://json-schema.org/understanding-json-schema/reference/object.html#additional-properties)).

> Would jsonschema be easily "summed"?

You can refer to objects in different schemas using `$ref`, but it is not as readable / explicit as the `myr` way.

That said, I agree with you that jsonschema is not a desirable input format. What you are describing in your metadata workflow, combined with your initial statement _"I want a specification that could be read and written by anyone (with a touch of training, of course), especially people who do not work outside of Google Docs, Word and occasionally PRISM"_ strongly reminds me of [linkml](linkml.io). 

While linkml is doing **a lot** more than what is actually needed here (auto-generating docs, code, schemas in multiple language), their input format seems to match your requirements. Below is an example based on [one of their tutorials](https://github.com/linkml/linkml-tutorial/blob/step_2_classes_and_slots/src/linkml_tutorial/schema/linkml_tutorial.yaml). Their [data model](https://linkml.io/linkml/schemas/models.html) is IMO expressive enough so that it can be read by anyone. It is not too verbose, so pretty comfortable to write. The tooling is a bit overwhelming (does many things), but can actually generate jsonschema _from_ this yaml file, so very similar to what you were describing.

```yaml
id: https://w3id.org/linkml/linkml-tutorial
name: linkml-tutorial

prefixes:
  linkml_tutorial: https://w3id.org/linkml/linkml-tutorial/

default_prefix: linkml_tutorial
default_range: string

imports:
  - linkml:types

classes:
  Person:
    slots:
      - id
      - name
      - age_in_years
      - birth date
      - pets

  Animal:
    slots:
      - id
      - name
      - species
      - age_in_years
      - birth date

slots:
  id:
    required: true
    range: uriorcurie
    description: A unique identifier for a person
  name:
    description: A human-readable name for a person
  birth date:
    range: date
    description: Date on which a person is born
  age_in_years:
    range: integer
    description: Number of years since birth
  pets:
    description: a collection of animals that lives with and is taken care of by a person.
    multivalued: true
    range: Animal

  species:
    description: The species of an animal

```
